################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal.c \
F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_adc.c \
F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_adc_ex.c \
F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_cortex.c \
F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_dma.c \
F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_flash.c \
F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_flash_ex.c \
F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_gpio.c \
F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_ipcc.c \
F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_pwr.c \
F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_pwr_ex.c \
F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rcc.c \
F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rcc_ex.c \
F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_uart.c \
F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_uart_ex.c 

OBJS += \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_adc.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_adc_ex.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_cortex.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_dma.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_flash.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_flash_ex.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_gpio.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_ipcc.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_pwr.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_pwr_ex.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_rcc.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_rcc_ex.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_uart.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_uart_ex.o 

C_DEPS += \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_adc.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_adc_ex.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_cortex.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_dma.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_flash.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_flash_ex.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_gpio.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_ipcc.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_pwr.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_pwr_ex.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_rcc.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_rcc_ex.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_uart.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_uart_ex.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal.o: F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal.c Drivers/STM32WBxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DMAC_802_15_4_WB -DCORE_CM4 -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../Utilities/sequencer -I../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../Middlewares/ST/STM32_WPAN/mac_802_15_4/core/inc -I../../STM32_WPAN/App -I../../Middlewares/ST/STM32_WPAN -I../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../STM32_WPAN/Target -I../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../Middlewares/ST/STM32_WPAN/utilities -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_adc.o: F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_adc.c Drivers/STM32WBxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DMAC_802_15_4_WB -DCORE_CM4 -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../Utilities/sequencer -I../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../Middlewares/ST/STM32_WPAN/mac_802_15_4/core/inc -I../../STM32_WPAN/App -I../../Middlewares/ST/STM32_WPAN -I../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../STM32_WPAN/Target -I../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../Middlewares/ST/STM32_WPAN/utilities -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_adc_ex.o: F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_adc_ex.c Drivers/STM32WBxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DMAC_802_15_4_WB -DCORE_CM4 -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../Utilities/sequencer -I../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../Middlewares/ST/STM32_WPAN/mac_802_15_4/core/inc -I../../STM32_WPAN/App -I../../Middlewares/ST/STM32_WPAN -I../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../STM32_WPAN/Target -I../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../Middlewares/ST/STM32_WPAN/utilities -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_cortex.o: F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_cortex.c Drivers/STM32WBxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DMAC_802_15_4_WB -DCORE_CM4 -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../Utilities/sequencer -I../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../Middlewares/ST/STM32_WPAN/mac_802_15_4/core/inc -I../../STM32_WPAN/App -I../../Middlewares/ST/STM32_WPAN -I../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../STM32_WPAN/Target -I../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../Middlewares/ST/STM32_WPAN/utilities -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_dma.o: F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_dma.c Drivers/STM32WBxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DMAC_802_15_4_WB -DCORE_CM4 -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../Utilities/sequencer -I../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../Middlewares/ST/STM32_WPAN/mac_802_15_4/core/inc -I../../STM32_WPAN/App -I../../Middlewares/ST/STM32_WPAN -I../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../STM32_WPAN/Target -I../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../Middlewares/ST/STM32_WPAN/utilities -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_flash.o: F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_flash.c Drivers/STM32WBxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DMAC_802_15_4_WB -DCORE_CM4 -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../Utilities/sequencer -I../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../Middlewares/ST/STM32_WPAN/mac_802_15_4/core/inc -I../../STM32_WPAN/App -I../../Middlewares/ST/STM32_WPAN -I../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../STM32_WPAN/Target -I../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../Middlewares/ST/STM32_WPAN/utilities -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_flash_ex.o: F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_flash_ex.c Drivers/STM32WBxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DMAC_802_15_4_WB -DCORE_CM4 -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../Utilities/sequencer -I../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../Middlewares/ST/STM32_WPAN/mac_802_15_4/core/inc -I../../STM32_WPAN/App -I../../Middlewares/ST/STM32_WPAN -I../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../STM32_WPAN/Target -I../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../Middlewares/ST/STM32_WPAN/utilities -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_gpio.o: F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_gpio.c Drivers/STM32WBxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DMAC_802_15_4_WB -DCORE_CM4 -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../Utilities/sequencer -I../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../Middlewares/ST/STM32_WPAN/mac_802_15_4/core/inc -I../../STM32_WPAN/App -I../../Middlewares/ST/STM32_WPAN -I../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../STM32_WPAN/Target -I../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../Middlewares/ST/STM32_WPAN/utilities -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_ipcc.o: F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_ipcc.c Drivers/STM32WBxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DMAC_802_15_4_WB -DCORE_CM4 -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../Utilities/sequencer -I../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../Middlewares/ST/STM32_WPAN/mac_802_15_4/core/inc -I../../STM32_WPAN/App -I../../Middlewares/ST/STM32_WPAN -I../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../STM32_WPAN/Target -I../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../Middlewares/ST/STM32_WPAN/utilities -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_pwr.o: F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_pwr.c Drivers/STM32WBxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DMAC_802_15_4_WB -DCORE_CM4 -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../Utilities/sequencer -I../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../Middlewares/ST/STM32_WPAN/mac_802_15_4/core/inc -I../../STM32_WPAN/App -I../../Middlewares/ST/STM32_WPAN -I../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../STM32_WPAN/Target -I../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../Middlewares/ST/STM32_WPAN/utilities -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_pwr_ex.o: F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_pwr_ex.c Drivers/STM32WBxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DMAC_802_15_4_WB -DCORE_CM4 -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../Utilities/sequencer -I../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../Middlewares/ST/STM32_WPAN/mac_802_15_4/core/inc -I../../STM32_WPAN/App -I../../Middlewares/ST/STM32_WPAN -I../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../STM32_WPAN/Target -I../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../Middlewares/ST/STM32_WPAN/utilities -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_rcc.o: F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rcc.c Drivers/STM32WBxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DMAC_802_15_4_WB -DCORE_CM4 -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../Utilities/sequencer -I../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../Middlewares/ST/STM32_WPAN/mac_802_15_4/core/inc -I../../STM32_WPAN/App -I../../Middlewares/ST/STM32_WPAN -I../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../STM32_WPAN/Target -I../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../Middlewares/ST/STM32_WPAN/utilities -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_rcc_ex.o: F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rcc_ex.c Drivers/STM32WBxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DMAC_802_15_4_WB -DCORE_CM4 -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../Utilities/sequencer -I../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../Middlewares/ST/STM32_WPAN/mac_802_15_4/core/inc -I../../STM32_WPAN/App -I../../Middlewares/ST/STM32_WPAN -I../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../STM32_WPAN/Target -I../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../Middlewares/ST/STM32_WPAN/utilities -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_uart.o: F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_uart.c Drivers/STM32WBxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DMAC_802_15_4_WB -DCORE_CM4 -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../Utilities/sequencer -I../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../Middlewares/ST/STM32_WPAN/mac_802_15_4/core/inc -I../../STM32_WPAN/App -I../../Middlewares/ST/STM32_WPAN -I../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../STM32_WPAN/Target -I../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../Middlewares/ST/STM32_WPAN/utilities -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_uart_ex.o: F:/MasterDiploma2/src_STM32/Mac_802_15_4_FFD/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_uart_ex.c Drivers/STM32WBxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DMAC_802_15_4_WB -DCORE_CM4 -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../Utilities/sequencer -I../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../Middlewares/ST/STM32_WPAN/mac_802_15_4/core/inc -I../../STM32_WPAN/App -I../../Middlewares/ST/STM32_WPAN -I../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../STM32_WPAN/Target -I../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../Middlewares/ST/STM32_WPAN/utilities -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Drivers-2f-STM32WBxx_HAL_Driver

clean-Drivers-2f-STM32WBxx_HAL_Driver:
	-$(RM) ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal.d ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal.o ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal.su ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_adc.d ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_adc.o ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_adc.su ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_adc_ex.d ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_adc_ex.o ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_adc_ex.su ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_cortex.d ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_cortex.o ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_cortex.su ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_dma.d ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_dma.o ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_dma.su ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_flash.d ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_flash.o ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_flash.su ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_flash_ex.d ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_flash_ex.o ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_flash_ex.su ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_gpio.d ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_gpio.o ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_gpio.su ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_ipcc.d ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_ipcc.o ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_ipcc.su ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_pwr.d ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_pwr.o ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_pwr.su ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_pwr_ex.d ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_pwr_ex.o ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_pwr_ex.su ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_rcc.d ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_rcc.o ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_rcc.su ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_rcc_ex.d ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_rcc_ex.o ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_rcc_ex.su ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_uart.d ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_uart.o ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_uart.su ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_uart_ex.d ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_uart_ex.o ./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_uart_ex.su

.PHONY: clean-Drivers-2f-STM32WBxx_HAL_Driver

